//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSociety.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hack_dbEntities : DbContext
    {
        public hack_dbEntities()
            : base("name=hack_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_LK_Gender> T_LK_Gender { get; set; }
        public virtual DbSet<T_LK_PetType> T_LK_PetType { get; set; }
        public virtual DbSet<T_Market> T_Market { get; set; }
        public virtual DbSet<T_Pet> T_Pet { get; set; }
        public virtual DbSet<T_Photo> T_Photo { get; set; }
        public virtual DbSet<T_Post> T_Post { get; set; }
        public virtual DbSet<T_User> T_User { get; set; }
    }
}
