//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSociety.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Post
    {
        public System.Guid PostID { get; set; }
        public string Title { get; set; }
        public string Desciption { get; set; }
        public Nullable<double> TimeSlotStart { get; set; }
        public Nullable<double> TimeSlotEnd { get; set; }
        public Nullable<int> PhotoID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<System.Guid> PetID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual T_Pet T_Pet { get; set; }
        public virtual T_Photo T_Photo { get; set; }
        public virtual T_User T_User { get; set; }
    }
}
